### ISSUE TITLE
parse `T20M` correctly

### ISSUE THREAD

**Issue by derhuerst** [LinusU/node-parse-iso-duration#1]
AFAIK `T20M` is a [valid ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by LinusU** [comment]
I'm quite sure it's not, although `PT20M` is and parses correctly to 20 minutes.

If you can point me to any specification in the standard that say you can skip the `P` I'll be happy to reconsider.

**Comment by derhuerst** [comment]
Actually I coudn't even find the ISO 8601 because [iso.org](http://www.iso.org/) is down, just [a "readable" summary](http://www.cl.cam.ac.uk/~mgk25/iso-time.html).
